// Regenerates app/engine/example-data.js (the example project shown on first open).
// Run: node app/tools/build-example.cjs
const fs = require("node:fs");
const path = require("node:path");
for (const f of ["core", "space", "models", "optimize", "analytics", "library"]) require(path.join(__dirname, "..", "engine", `${f}.js`));
const p = globalThis.BC.simulateExample();
const out = `/* Generated by app/tools/build-example.cjs. Simulated results, not real tastings. */
(function () { const BC = (globalThis.BC = globalThis.BC || {}); BC.EXAMPLE_PROJECT = ${JSON.stringify(p)}; })();
`;
fs.writeFileSync(path.join(__dirname, "..", "engine", "example-data.js"), out);
console.log(`example: ${p.runs.length} runs, ${out.length} bytes`);
